services:
  app:
    build: .
    container_name: ordering-app
    image: ordering-application:latest
    ports:
      - "8080:8080"
    environment:
      - API_HOST=0.0.0.0
      - API_PORT=8080
      - DISPLAY=host.docker.internal:0.0
    restart: "no"
    extra_hosts:
      - "host.docker.internal:host-gateway"
