name: ordering-application
title: Ordering Application
base: core22
version: '1.0.0'
summary: Cafe ordering application
description: |
  Cafe ordering application with REST API and Tkinter GUI.
  Built for Operativni sustavi course at Mathos.

license: MIT
contact: patriciaribic27@gmail.com
source-code: https://github.com/patriciaribic27/Ordering-Application-Docker-Snap

grade: stable
confinement: strict

apps:
  api-server:
    command: bin/python3 $SNAP/app/services/api_server.py
    daemon: simple
    install-mode: enable
    plugs:
      - network
      - network-bind
    environment:
      API_HOST: "0.0.0.0"
      API_PORT: "8080"
      PYTHONPATH: "$SNAP/app:$SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3.10/lib-dynload"

  gui-app:
    command: bin/python3 $SNAP/app/gui/tablet_gui.py
    plugs:
      - x11
      - wayland
      - desktop
      - desktop-legacy
      - home
      - network
    environment:
      PYTHONPATH: "$SNAP/app:$SNAP/lib/python3.10/site-packages:$SNAP/usr/lib/python3/dist-packages:$SNAP/usr/lib/python3.10:$SNAP/usr/lib/python3.10/lib-dynload"
      TCL_LIBRARY: "$SNAP/usr/share/tcltk/tcl8.6"
      TK_LIBRARY: "$SNAP/usr/share/tcltk/tk8.6"

parts:
  python-deps:
    plugin: python
    source: .
    python-packages:
      - aiohttp
      - reportlab
    stage-packages:
      - python3-venv
      - python3
      - python3-tk
      - python3-aiohttp
      - tcl8.6
      - tk8.6
      - libx11-6
      - libxext6
      - libxrender1
      - libxtst6
      - libxi6
     

  app-files:
    plugin: dump
    source: .
    organize:
      main.py: app/main.py
      gui: app/gui
      services: app/services
      models: app/models
      decorators: app/decorators
      exporters: app/exporters
      requirements.txt: app/requirements.txt
      README.md: app/README.md  

